<?php

use Magento\Framework\View\Element\Template;

/** @var Template $block */
?>
<ul>
    <li>Task1</li>
    <li>Task2</li>
    <li>Task3</li>
</ul>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "todo": {
                        "component": "MageMastery_Todo/js/view/todo"
                    }
                }
            }
        }
    }
</script>
